//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct TVDBUser: APIModel {

    public let favoritesDisplaymode: String?

    public let language: String?

    public let userName: String?

    public init(favoritesDisplaymode: String? = nil, language: String? = nil, userName: String? = nil) {
        self.favoritesDisplaymode = favoritesDisplaymode
        self.language = language
        self.userName = userName
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        favoritesDisplaymode = try container.decodeIfPresent("favoritesDisplaymode")
        language = try container.decodeIfPresent("language")
        userName = try container.decodeIfPresent("userName")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(favoritesDisplaymode, forKey: "favoritesDisplaymode")
        try container.encodeIfPresent(language, forKey: "language")
        try container.encodeIfPresent(userName, forKey: "userName")
    }

}
