//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct TVDBSeriesImagesCount: APIModel {

    public let fanart: Int?

    public let poster: Int?

    public let season: Int?

    public let seasonwide: Int?

    public let series: Int?

    public init(fanart: Int? = nil, poster: Int? = nil, season: Int? = nil, seasonwide: Int? = nil, series: Int? = nil) {
        self.fanart = fanart
        self.poster = poster
        self.season = season
        self.seasonwide = seasonwide
        self.series = series
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        fanart = try container.decodeIfPresent("fanart")
        poster = try container.decodeIfPresent("poster")
        season = try container.decodeIfPresent("season")
        seasonwide = try container.decodeIfPresent("seasonwide")
        series = try container.decodeIfPresent("series")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(fanart, forKey: "fanart")
        try container.encodeIfPresent(poster, forKey: "poster")
        try container.encodeIfPresent(season, forKey: "season")
        try container.encodeIfPresent(seasonwide, forKey: "seasonwide")
        try container.encodeIfPresent(series, forKey: "series")
    }

}
