//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct TVDBUserRatings: APIModel {

    public let rating: Int?

    public let ratingItemId: Int?

    public let ratingType: String?

    public init(rating: Int? = nil, ratingItemId: Int? = nil, ratingType: String? = nil) {
        self.rating = rating
        self.ratingItemId = ratingItemId
        self.ratingType = ratingType
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        rating = try container.decodeIfPresent("rating")
        ratingItemId = try container.decodeIfPresent("ratingItemId")
        ratingType = try container.decodeIfPresent("ratingType")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(rating, forKey: "rating")
        try container.encodeIfPresent(ratingItemId, forKey: "ratingItemId")
        try container.encodeIfPresent(ratingType, forKey: "ratingType")
    }

}
