//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct TVDBEpisodeRecordData: APIModel {

    public let data: TVDBEpisode?

    public let errors: TVDBJSONErrors?

    public init(data: TVDBEpisode? = nil, errors: TVDBJSONErrors? = nil) {
        self.data = data
        self.errors = errors
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        data = try container.decodeIfPresent("data")
        errors = try container.decodeIfPresent("errors")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(data, forKey: "data")
        try container.encodeIfPresent(errors, forKey: "errors")
    }

}
